### ISSUE TITLE
我想要编写Kahla CLI

### ISSUE THREAD

**Issue by Xiangrui2019** [AiursoftWeb/Kahla.CLI#1]

**Comment by Anduin2017** [comment]
OK. Please open pull requests directly.

**Comment by ganlvtech** [comment]
@Xiangrui2019 Which language do you want to use?

**Comment by Xiangrui2019** [comment]
C#

**Comment by Anduin2017** [comment]
C# makes calling Aiursoft API easy because our SDK Aiursoft.Pylon already provided enough examples and useful methods for calling Aiursoft provided APIs. However, not all users' computer installs .NET Core runtime. Which makes the app hard to distribute.

**Comment by Xiangrui2019** [comment]
.net core 3.0 to build exe file

**Comment by Xiangrui2019** [comment]
.net core 3.0 can build exe file

**Comment by Anduin2017** [comment]
We are not building something for Windows. But for all possible developers and servers.

**Comment by Xiangrui2019** [comment]
Python 如何

**Comment by Xiangrui2019** [comment]
我找到了Python处理Cookie的方法
或者Go也是不错的

**Comment by ganlvtech** [comment]
如果在输入的时候来了一条消息，这怎么办？是像 vim 一样独占一块屏幕，重复擦除写入，而不是正常的输入输出。

**Comment by Anduin2017** [comment]
卡拉CLI肯定是两个独立的项目，一个是命令行，没有生命的，执行即退，像git。
另一个是监听器，有生命的，执行即挂着……

监听器你已经用Go写完了，当然我想最后fork过来
而这个项目，其实是不负责监听器的，只有一个无生命的命令行工具。

**Comment by ganlvtech** [comment]
比如 Linux 下就可以用 bg 让他后台运行，但又不影响输出，是这个意思吧。

**Comment by Xiangrui2019** [comment]
![image](https://user-images.githubusercontent.com/48279726/56072561-fb282580-5dca-11e9-9a6e-8a92acc87f72.png)
我用python编写
我用MVC模式开发
