### ISSUE TITLE
Kahla CLI was unable to send images

### ISSUE THREAD

**Issue by Xiangrui2019** [AiursoftWeb/Kahla.CLI#11]
I want KahlaCLI support to send images

**Comment by Xiangrui2019** [comment]
Let's discuss whether the following functionality should be added

**Comment by Anduin2017** [comment]
I don't need that function. Perhaps some bot developers may need to send images to their followers.

Can't send image is accepable.

**Comment by Xiangrui2019** [comment]
Oh

**Comment by Xiangrui2019** [comment]
So whether you need it or not

**Comment by Xiangrui2019** [comment]
？

**Comment by Xiangrui2019** [comment]
Close
